### ISSUE TITLE
Unable to run examples

### ISSUE THREAD

**Issue by ghost** [hwangjt/GeoMACH#15]
I have tried to run the conventional example, and received the following error:
/GeoMACH-master/GeoMACH/PGM/components/PGMinterpolant.py:102: RuntimeWarning: invalid value encountered in true_divide
  cross[: , ind] /= norms
trying to run any other example has no results.

**Comment by hwangjt** [comment]
That is a warning that can be ignored - it should only impact things if you are trying to perform shape optimization where the B-spline control points are allowed to move normal to the local surface.
It likely printed the warning, wrote the iges and tecplot output files, and terminated. If so this is the expected behavior. Tecplot or a some other visualization software is necessary to see the output

**Comment by geomach** [comment]
Shots on
